easy_admin:
    site_name: 'Portfolio'
    entities:
        # List the entity class name you want to manage
        Image:
            class: App\Entity\Image
            form:
                fields:
                    - { property: 'name', type: 'file_upload' }
                    - { property: 'alt'}
            list:
                fields:
                    - { property: 'name', type: 'image' }
                    - { property: 'alt'}

        Skill:
            class: App\Entity\Skill

        User:
            class: App\Entity\User
